Feature/sprint
Irsn11/Unit2 pull request #3
Opened 2021-03-08 17:22 UTC by Irsn11

Спринт 2
- Вёрстка макета с применением БЭМ методологии, блоки:**(done)**
    - Популярные услуги **(done)**
    - Услуги и цены**(done)**
    - Мастера**(done)**
- Адаптивить шапку под мобильные устройства **( not yet)**
- Использование препроцессора SASS в нотации SCSS**(done)**
- Подключить Gulp, собрать вёрстку**(done)**

2021-03-09 08:40 UTC, studenttsu requested changes
Привет) Хорошая работа!
Осталось поправить пару моментов.

Не забывай pr с аппрувом сливать в master.

Дожать адаптив шапки можно отдельным pr.

2021-03-09 08:40 UTC, studenttsu commented on src/scss/main.scss
> +.header__top {
`нужно поправить`

В проекте уже есть sass, удобно пользоваться вложенностью. Давай объединим по смыслу связанные стили.
Это .header, .about, .preview, .footer, ....

```
.header {
  &__top {
    ...
  }
}
```

2021-03-09 08:40 UTC, studenttsu commented on src/scss/main.scss
> +@media screen and (max-width: 768px) {
`можно лучше`

свойства медиа-запросов удобней хранить в отдельном файле

2021-03-09 08:40 UTC, studenttsu commented on src/scss/main.scss
> +	&-2 {
`можно лучше`

не совсем понравилось именование - сразу не понятно что делает модификатор.

В целом предлагаю между блоками использовать одинаковое расстояния для отступа

2021-03-09 08:40 UTC, studenttsu commented on src/scss/main.scss
> +h2 {
`можно лучше`

глобальные стили лучше выносить наверх файла стилей

2021-03-09 08:40 UTC, studenttsu commented on src/index.html
> +			<section class="section section-color">
`нужно поправить`

модификаторы именуются через `_`

`section-color` - сразу и не поймёшь что делает модификатор

`section_grey` - более удачное название

2021-03-09 15:39 UTC, Irsn11 commented on src/scss/main.scss
> +	&-2 {
в секции price содержатся элементы которые имеют свой margin-bottom, если предполагать что карточки будут добавляться то у последних элементов нижний отступ лучше не убирать.

2021-03-10 04:06 UTC, studenttsu approved these changes
Спачибо за отличную работу!

2021-03-10 13:33 UTC, merged